direction: right

Authoring: {
  class: group

  Generation: {
    class: accent
  }

  Augmentation: {
    class: accent
  }

  Enrichment: {
    class: accent
  }

  Signing: {
    class: accent
    style: {
      stroke-dash: 3
    }
  }

  Generation -> Augmentation: {
    class: flow-pink
  }

  Augmentation -> Enrichment: {
    class: flow-pink
  }

  Enrichment -> Signing: {
    class: flow-pink
  }
}

Distribution: {
  class: accent
}

Analysis: {
  class: accent
}

Authoring.Signing -> Distribution: {
  class: flow-pink
}

Distribution -> Analysis: {
  class: flow-pink
}
