direction: right

generate: "Generate" {
  class: group

  ci: CI/CD\nPipeline {
    class: primary
    icon: node_modules/@tabler/icons/icons/outline/brand-github.svg
    width: 140
    height: 100
  }

  tool: SBOM Tool {
    class: highlight
    icon: node_modules/@tabler/icons/icons/outline/scan.svg
    width: 130
    height: 90
  }

  ci -> tool: build triggers {class: flow}
}

store: "Store" {
  class: group

  sbom: SBOM\nRepository {
    class: highlight
    icon: node_modules/@tabler/icons/icons/outline/database.svg
    width: 140
    height: 100
  }

  version: Version\nTracking {
    class: primary
    icon: node_modules/@tabler/icons/icons/outline/clock.svg
    width: 140
    height: 100
  }
}

monitor: "Monitor" {
  class: group

  vuln: Vulnerability\nDatabases {
    class: accent
    icon: node_modules/@tabler/icons/icons/outline/alert-triangle.svg
    width: 150
    height: 100
  }

  license: License\nCompliance {
    class: primary
    icon: node_modules/@tabler/icons/icons/outline/certificate.svg
    width: 150
    height: 100
  }
}

act: "Act" {
  class: group

  alert: Alert &\nTriage {
    class: accent
    icon: node_modules/@tabler/icons/icons/outline/bell-ringing.svg
    width: 130
    height: 100
  }

  fix: Remediate {
    class: highlight
    icon: node_modules/@tabler/icons/icons/outline/check.svg
    width: 130
    height: 90
  }
}

generate.tool -> store.sbom: store {class: flow}
store.sbom -> store.version: {class: flow}
store.sbom -> monitor.vuln: match {class: flow}
store.sbom -> monitor.license: check {class: flow}
monitor.vuln -> act.alert: notify {class: flow-pink}
act.alert -> act.fix: prioritize {class: flow-pink}
act.fix -> generate.ci: update & rebuild {class: flow-pink}
