direction: right

CI: {
  class: group
  label: "CI/CD Pipeline"

  Generate: {
    class: primary
    label: "Generate"
    icon: node_modules/@tabler/icons/icons/outline/settings-cog.svg
  }

  Enrich: {
    class: secondary
    label: "Enrich & Augment"
    icon: node_modules/@tabler/icons/icons/outline/wand.svg
  }

  Sign: {
    class: accent
    label: "Sign"
    icon: node_modules/@tabler/icons/icons/outline/signature.svg
  }

  Generate -> Enrich: {
    class: flow
  }

  Enrich -> Sign: {
    class: flow
  }
}

sbomify: {
  shape: image
  icon: assets/images/logo/logo-circle.svg
  width: 60
  height: 60
}

Analysis: {
  class: accent
  label: "Analysis"
  icon: node_modules/@tabler/icons/icons/outline/chart-line.svg
}

CI.Sign -> sbomify: Upload {
  class: flow
}

sbomify -> Analysis: Sync {
  class: flow
}
