direction: right

Software Product: {
  class: group
  label: "Modern Application"
  direction: down

  Transitive: {
    class: secondary
    label: "Transitive Dependencies"
    icon: node_modules/@tabler/icons/icons/filled/stack.svg
  }

  Open Source: {
    class: accent
    label: "Open Source Libraries"
    icon: node_modules/@tabler/icons/icons/outline/git-branch.svg
  }

  Source Code: {
    class: primary
    label: "Your Source Code"
    icon: node_modules/@tabler/icons/icons/outline/code.svg
  }

  Transitive -> Open Source: "included in" {
    class: flow-pink
  }

  Open Source -> Source Code: "included in" {
    class: flow
  }
}

SBOM: {
  class: highlight
  label: "SBOM\n(Ingredients List)"
  icon: node_modules/@tabler/icons/icons/outline/checklist.svg
}

Software Product -> SBOM: "Cataloged by" {
  class: flow
}
