direction: right

Zero: {
  class: secondary
  label: "Zero"
  icon: node_modules/@tabler/icons/icons/outline/help-circle.svg
}

Learn: {
  class: primary
  label: "Learn"
  icon: node_modules/@tabler/icons/icons/outline/book.svg
}

Generate: {
  class: accent
  label: "Generate"
  icon: node_modules/@tabler/icons/icons/outline/settings-cog.svg
}

Manage: {
  class: accent
  label: "Manage"
  icon: node_modules/@tabler/icons/icons/outline/folders.svg
}

Hero: {
  class: highlight
  label: "Hero"
  icon: node_modules/@tabler/icons/icons/filled/rosette-discount-check.svg
}

Zero -> Learn: {
  class: flow
}

Learn -> Generate: {
  class: flow
}

Generate -> Manage: {
  class: flow
}

Manage -> Hero: {
  class: flow-pink
}
