direction: right

Generate: {
  class: primary
  label: "Generate"
}

Manage: {
  class: accent
  label: "Manage"
}

Share: {
  class: secondary
  label: "Share"
}

Generate -> Manage: CI/CD {
  class: flow
}

Manage -> Share: Trust Center {
  class: flow
}

